"""
Memory DB Service for Sathya Agencies Medical Agent (Doxy).

Implements a 2-Tier Hybrid Memory Architecture on Neon PostgreSQL:
- Tier 1 (Deterministic Customer Profile):
    Keyed by normalized phone number.
    Stores and retrieves customer name, phone, and complete delivery address from the `customers` table.
    Ensures that once a customer provides their address, Doxy remembers it permanently and never asks again.

- Tier 2 (Semantic & Episodic Memory via pgvector):
    Keyed by normalized phone number.
    Stores past orders, conversation context, special requests, and medical preferences as 768-dimensional
    vector embeddings generated by Gemini (`gemini-embedding-001`).
    Allows semantic recall (e.g. "What tonic did I order last time?", "Send the usual fever tablets").
"""

import os
import re
import json
import logging
from typing import Optional, List, Dict, Any
from dotenv import load_dotenv

import psycopg
from pgvector.psycopg import register_vector
from google import genai
from google.genai import types

# Robustly load both medical-agent/.env and root/.env
_curr_dir = os.path.dirname(os.path.abspath(__file__))
_agent_env = os.path.abspath(os.path.join(_curr_dir, "..", ".env"))
_root_env = os.path.abspath(os.path.join(_curr_dir, "..", "..", ".env"))

if os.path.exists(_agent_env):
    load_dotenv(_agent_env, override=False)
if os.path.exists(_root_env):
    load_dotenv(_root_env, override=False)
load_dotenv()

logger = logging.getLogger("memory_db")
if not logger.handlers:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")

_db_initialized = False
_gemini_client = None


def get_db_url() -> str:
    """Retrieve the PostgreSQL connection string."""
    url = os.getenv("NEON_DB_URL", "")
    if not url:
        logger.warning("NEON_DB_URL is not set in environment!")
    return url


def get_gemini_client() -> genai.Client:
    """Get or initialize the Google GenAI client for embeddings."""
    global _gemini_client
    if _gemini_client is None:
        api_key = os.getenv("GEMINI_API_KEY")
        _gemini_client = genai.Client(api_key=api_key)
    return _gemini_client


def normalize_phone(phone_or_id: Optional[str]) -> str:
    """
    Normalize Indian phone numbers to standard 10 digits.
    Handles:
    - '+91 98765 43210' -> '9876543210'
    - '919876543210' (WhatsApp JID/ID) -> '9876543210'
    - '09876543210' -> '9876543210'
    - '9876543210' -> '9876543210'
    """
    if not phone_or_id:
        return ""
    digits = re.sub(r"\D", "", str(phone_or_id).strip())
    if len(digits) == 12 and digits.startswith("91"):
        return digits[2:]
    if len(digits) == 11 and digits.startswith("0"):
        return digits[1:]
    if len(digits) >= 10:
        return digits[-10:]
    return digits


def get_connection():
    """Create a psycopg connection with pgvector registered."""
    url = get_db_url()
    if not url:
        raise ValueError("NEON_DB_URL is not configured")
    conn = psycopg.connect(url, autocommit=True)
    register_vector(conn)
    return conn


def init_memory_db():
    """
    Ensure the vector extension and agent_memories table exist in PostgreSQL.
    Safe to call repeatedly on startup.
    """
    global _db_initialized
    if _db_initialized:
        return

    url = get_db_url()
    if not url:
        logger.warning("Cannot initialize Memory DB: NEON_DB_URL not found.")
        return

    try:
        with psycopg.connect(url, autocommit=True) as conn:
            with conn.cursor() as cur:
                # 1. Enable pgvector extension
                cur.execute("CREATE EXTENSION IF NOT EXISTS vector;")

                # 2. Create agent_memories table
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS agent_memories (
                        memory_id SERIAL PRIMARY KEY,
                        phone VARCHAR(50) NOT NULL,
                        customer_id VARCHAR(50),
                        memory_type VARCHAR(50) DEFAULT 'general',
                        content TEXT NOT NULL,
                        embedding vector(768),
                        metadata JSONB DEFAULT '{}'::jsonb,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    );
                """)

                # 3. Create indexes
                cur.execute("CREATE INDEX IF NOT EXISTS idx_agent_memories_phone ON agent_memories(phone);")
                cur.execute("CREATE INDEX IF NOT EXISTS idx_agent_memories_customer_id ON agent_memories(customer_id);")
                cur.execute("CREATE INDEX IF NOT EXISTS idx_agent_memories_type ON agent_memories(memory_type);")

                # Ensure index on customers.phone
                cur.execute("CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);")

        _db_initialized = True
        logger.info("Memory DB & pgvector initialized successfully on Neon PostgreSQL.")
    except Exception as e:
        logger.error(f"Error initializing Memory DB: {e}")


# ==============================================================================
# TIER 1: DETERMINISTIC CUSTOMER PROFILE (Exact Name, Phone & Saved Address)
# ==============================================================================

def get_customer_profile(phone_or_customer_id: str) -> Optional[Dict[str, Any]]:
    """
    Look up a customer's profile by their phone number.
    Checks:
    1. `customers` table in PostgreSQL.
    2. Fallback to `agent_orders` for previous verified delivery address.
    Returns:
        {"name": ..., "phone": ..., "address": ..., "customer_id": ...} or None
    """
    if not phone_or_customer_id:
        return None

    init_memory_db()
    norm_phone = normalize_phone(phone_or_customer_id)
    raw_id = str(phone_or_customer_id).strip()

    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                # 1. Check customers table
                if norm_phone and len(norm_phone) == 10:
                    cur.execute(
                        """
                        SELECT customer_id, name, phone, address
                        FROM customers
                        WHERE phone = %s OR phone = %s OR phone LIKE %s
                        ORDER BY customer_id DESC LIMIT 1;
                        """,
                        (norm_phone, f"91{norm_phone}", f"%{norm_phone}"),
                    )
                    row = cur.fetchone()
                    if row and row[3]:  # if address exists
                        return {
                            "customer_id": str(row[0]),
                            "name": row[1] or "",
                            "phone": norm_phone,
                            "address": row[3].strip() if row[3] else "",
                            "source": "customers",
                        }

                # 2. Check agent_orders table for last confirmed address
                cur.execute(
                    """
                    SELECT customer_id, customer_name, phone, delivery_address
                    FROM agent_orders
                    WHERE (phone = %s OR phone LIKE %s OR customer_id = %s)
                      AND delivery_address IS NOT NULL
                      AND LENGTH(TRIM(delivery_address)) > 10
                    ORDER BY order_id DESC LIMIT 1;
                    """,
                    (norm_phone, f"%{norm_phone}%", raw_id),
                )
                row = cur.fetchone()
                if row and row[3]:
                    return {
                        "customer_id": row[0] or raw_id,
                        "name": row[1] or "",
                        "phone": norm_phone or row[2],
                        "address": row[3].strip(),
                        "source": "agent_orders",
                    }

    except Exception as e:
        logger.warning(f"Error reading customer profile from DB: {e}")

    return None


def save_customer_profile(
    phone_or_customer_id: str,
    name: Optional[str] = None,
    address: Optional[str] = None,
    customer_id: Optional[str] = None,
) -> bool:
    """
    Save or update customer profile in PostgreSQL (`customers` table).
    Keyed by normalized 10-digit phone number.
    """
    norm_phone = normalize_phone(phone_or_customer_id)
    if not norm_phone or len(norm_phone) < 10:
        if customer_id:
            norm_phone = normalize_phone(customer_id)
    if not norm_phone or len(norm_phone) < 10:
        return False

    clean_name = name.strip() if name and name.strip() else None
    clean_address = address.strip() if address and address.strip() else None

    # Don't overwrite with empty address/name
    if not clean_address and not clean_name:
        return False

    init_memory_db()

    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                # Check if customer exists by phone
                cur.execute(
                    "SELECT customer_id, name, address FROM customers WHERE phone = %s OR phone = %s LIMIT 1;",
                    (norm_phone, f"91{norm_phone}"),
                )
                existing = cur.fetchone()

                if existing:
                    cust_id = existing[0]
                    cur.execute(
                        """
                        UPDATE customers
                        SET name = COALESCE(%s, name),
                            address = COALESCE(%s, address),
                            updated_at = CURRENT_TIMESTAMP
                        WHERE customer_id = %s;
                        """,
                        (clean_name, clean_address, cust_id),
                    )
                    logger.info(f"Updated customer profile for phone {norm_phone}: name={clean_name}, addr={clean_address}")
                else:
                    cur.execute(
                        """
                        INSERT INTO customers (name, phone, address)
                        VALUES (%s, %s, %s);
                        """,
                        (clean_name or "Customer", norm_phone, clean_address or ""),
                    )
                    logger.info(f"Created new customer profile for phone {norm_phone}: name={clean_name}")

                return True
    except Exception as e:
        logger.error(f"Error saving customer profile to DB: {e}")
        return False


# ==============================================================================
# TIER 2: SEMANTIC & EPISODIC MEMORY (pgvector)
# ==============================================================================

def generate_embedding(text: str) -> Optional[List[float]]:
    """
    Generate 768-dimensional embedding vector for text using Gemini.
    Uses `gemini-embedding-001` with `output_dimensionality=768`.
    """
    if not text or not str(text).strip():
        return None

    try:
        client = get_gemini_client()
        res = client.models.embed_content(
            model="gemini-embedding-001",
            contents=text.strip(),
            config=types.EmbedContentConfig(output_dimensionality=768),
        )
        if res and res.embeddings and len(res.embeddings) > 0:
            return res.embeddings[0].values
    except Exception as e:
        logger.error(f"Error generating embedding via Gemini: {e}")

    return None


def store_memory(
    phone_or_customer_id: str,
    content: str,
    memory_type: str = "general",
    metadata: Optional[Dict[str, Any]] = None,
    customer_id: Optional[str] = None,
) -> Optional[int]:
    """
    Store an episodic memory, order summary, customer preference, or note into `agent_memories`.
    Generates embedding and writes to PostgreSQL with pgvector.
    """
    if not content or not content.strip():
        return None

    norm_phone = normalize_phone(phone_or_customer_id)
    cust_id = customer_id or str(phone_or_customer_id)

    init_memory_db()

    embedding = generate_embedding(content)
    if not embedding:
        logger.warning("Failed to generate embedding for memory; storing without vector.")

    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO agent_memories (phone, customer_id, memory_type, content, embedding, metadata)
                    VALUES (%s, %s, %s, %s, %s, %s)
                    RETURNING memory_id;
                    """,
                    (
                        norm_phone,
                        cust_id,
                        memory_type,
                        content.strip(),
                        embedding,
                        json.dumps(metadata or {}, ensure_ascii=False),
                    ),
                )
                row = cur.fetchone()
                mem_id = row[0] if row else None
                logger.info(f"Stored {memory_type} memory (id={mem_id}) for phone {norm_phone}: {content[:60]}...")
                return mem_id
    except Exception as e:
        logger.error(f"Error storing memory to DB: {e}")
        return None


def search_memories(
    phone_or_customer_id: str,
    query: str,
    limit: int = 3,
    threshold: float = 0.45,
    memory_type: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """
    Semantic search over customer memories using pgvector cosine distance `<=>`.
    Returns most relevant memories filtered for this customer's phone number.
    """
    if not query or not query.strip():
        return []

    norm_phone = normalize_phone(phone_or_customer_id)
    cust_id = str(phone_or_customer_id).strip()

    init_memory_db()
    query_vec = generate_embedding(query)
    if not query_vec:
        return []

    results = []
    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                type_filter = "AND memory_type = %s" if memory_type else ""
                params = [query_vec, norm_phone, cust_id]
                if memory_type:
                    params.append(memory_type)
                params.extend([query_vec, limit])

                cur.execute(
                    f"""
                    SELECT memory_id, memory_type, content, metadata, created_at,
                           1 - (embedding <=> %s::vector) AS similarity
                    FROM agent_memories
                    WHERE (phone = %s OR customer_id = %s)
                      AND embedding IS NOT NULL
                      {type_filter}
                    ORDER BY embedding <=> %s::vector ASC
                    LIMIT %s;
                    """,
                    params,
                )
                rows = cur.fetchall()
                for r in rows:
                    similarity = float(r[5]) if r[5] is not None else 0.0
                    if similarity >= threshold:
                        results.append({
                            "memory_id": r[0],
                            "memory_type": r[1],
                            "content": r[2],
                            "metadata": r[3] if isinstance(r[3], dict) else {},
                            "created_at": str(r[4]),
                            "similarity": round(similarity, 3),
                        })
    except Exception as e:
        logger.error(f"Error searching memories: {e}")

    return results


def get_customer_preferences(phone_or_customer_id: str, limit: int = 5) -> List[str]:
    """
    Retrieve stored customer preferences and special notes for a customer by phone number.
    Used for pre-prompting the agent with known customer preferences.
    """
    norm_phone = normalize_phone(phone_or_customer_id)
    if not norm_phone:
        return []

    init_memory_db()
    prefs = []
    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT content FROM agent_memories
                    WHERE phone = %s AND memory_type IN ('preference', 'note', 'medical_note')
                    ORDER BY memory_id DESC
                    LIMIT %s;
                    """,
                    (norm_phone, limit),
                )
                rows = cur.fetchall()
                for r in rows:
                    if r[0] and r[0].strip():
                        prefs.append(r[0].strip())
    except Exception as e:
        logger.warning(f"Error fetching customer preferences: {e}")

    return prefs
